import EventEmitter from "events";

export const EVENTS = {
  USER_REGISTERED: "USER_REGISTERED",

  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_RECEIVED: "ORDER_RECEIVED",

  ORDER_PAYMENT_PENDING:
    "ORDER_PAYMENT_PENDING",

  ORDER_PAYMENT_FAILED:
    "ORDER_PAYMENT_FAILED",

  RMA_REQUESTED: "RMA_REQUESTED",

  RMA_REVERSE_PICKUP_BOOKED:
    "RMA_REVERSE_PICKUP_BOOKED",

  CUSTOMER_CREDIT_CREDITED:
    "CUSTOMER_CREDIT_CREDITED",
};

export const eventBus = new EventEmitter();

eventBus.setMaxListeners(25);
